log_level = "warning"

[[runners]]
  name = "shell-rpi"
  url = "https://gitlab.14traits.dev"
  executor = "ssh"
  token = "glrt-ZzoyCm86MQp0OjIKdToxEI-zFDGRoWZF-HyxosCMvBA.171jxxqac"  # add your registration token here
  limit = 2
  shell = "bash"

[[runners]]
  name = "docker-rpi"
  url = "https://gitlab.14traits.dev"  # change to your GitLab instance URL
  executor = "docker"
  token = "glrt-ZzoyCm86MQp0OjIKdToxEI-zFDGRoWZF-HyxosCMvBA.171jxxqac"  # add your registration token here
  limit = 2
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
  [runners.cache]
    Insecure = false